repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "(?x)^(.*/migrations/.*)$"
      - id: end-of-file-fixer
        exclude: "(?x)^(.*/migrations/.*)$"
      - id: check-docstring-first
        exclude: "(?x)^(.*/migrations/.*)$"
      - id: check-merge-conflict
        exclude: "(?x)^(.*/migrations/.*)$"
      - id: requirements-txt-fixer
        exclude: "(?x)^(.*/migrations/.*)$"
      - id: name-tests-test
        args: ["--django"]
        exclude: "(?x)^(.*/migrations/.*)$"
  # - repo: https://gitlab.com/PyCQA/flake8
  #   rev: 3.8.4
  #   hooks:
  #     - id: flake8
  #       args:
  #         - "--max-line-length=100"
  #         - "--count"
  #         - "--statistics"
  #         - "--format=pylint"
  #       exclude: "(?x)^(.*/migrations/.*)$"
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    - id: isort
      # args: ['--silent-overwrite']
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.5.4" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
        args:
          - "--in-place"
        exclude: "(?x)^(.*/migrations/.*)$"
  - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: "v0.3.3" # Use the sha / tag you want to point at
    hooks:
      - id: pep257
        name: Docstring related PEP-257 checks.
        exclude: "(?x)^(.*/migrations/.*)$"
  - repo: local
    hooks:
      - id: local-lint
        name: Local pylint
        language: system
        entry: pylint --load-plugins pylint_django --rcfile=.pylintrc --fail-under=4
        types:
          - "python"
        exclude: "(?x)^(.*/migrations/.*)$"
